-- HowdyScout 2026 — REBUILT™ Edition
-- Azure SQL: sbrondel.database.windows.net / howdyscout2026
-- This file documents the REAL table structure.
-- Tables are managed externally; this is reference-only.

-- =============================================
-- frc6377Events  (READ-ONLY for powerbi user)
-- =============================================
-- internal_key   VARCHAR  PK
-- event_key      VARCHAR  (e.g. '2026txcle', '2026howdy')
-- event_name     VARCHAR  (e.g. 'Space City #1')
-- start_date     VARCHAR
-- end_date       VARCHAR
-- alliance_picks VARCHAR  (nullable)

-- Seeded events used by HowdyScout:
--   2026howdy  → HowdyScout Practice   (Houston, TX)
--   2026txcle  → Space City #1         (Houston, TX)  ← TBA: 2026txcle
--   2026txman  → Manor District        (Manor, TX)    ← TBA: 2026txman

-- =============================================
-- frc6377MatchScouting  (READ + INSERT for powerbi user)
-- =============================================
-- id                     INT        IDENTITY PK
-- primary_key            VARCHAR    '{team}-{match_key}-{scouted_by}'
-- frc_team               VARCHAR    team number as string (no 'frc' prefix)
-- event_key              VARCHAR    FK → frc6377Events.event_key
-- match_key              VARCHAR    e.g. '2026txcle_qm5'
-- driver_station         VARCHAR    e.g. 'red1', 'blue3'
-- comp_level             VARCHAR    'qm' | 'qf' | 'sf' | 'f'
-- match_number           INT
-- auto_moved             VARCHAR    'Yes' | 'No'
-- auto_fuel_scored       INT
-- auto_fuel_missed       INT
-- auto_climb_level       VARCHAR    'No Attempt' | 'Level1'
-- auto_climb_position    VARCHAR    'No Attempt' | positional label
-- tele_fuel_scored       INT
-- tele_fuel_missed       INT
-- tele_human_fuel_scored INT
-- tele_human_fuel_missed INT
-- tele_climb_level       VARCHAR    'No Attempt' | 'Level1' | 'Level2' | 'Level3'
-- tele_climb_position    VARCHAR    'No Attempt' | positional label
-- defender_rating        INT        0–5
-- mech_failure           VARCHAR    'Yes' | 'No'
-- scouted_by             VARCHAR

-- =============================================
-- EventMatches  (schedule, READ-ONLY)
-- =============================================
-- ID             INT  IDENTITY PK
-- internal_key   VARCHAR
-- event_key      VARCHAR
-- match_key      VARCHAR
-- comp_level     VARCHAR
-- match_number   INT
-- blue1..blue3   VARCHAR  team numbers
-- red1..red3     VARCHAR  team numbers
-- predicted_time INT      (epoch ms, nullable)

-- =============================================
-- Teams
-- =============================================
-- frc_team     VARCHAR  PK (e.g. '254')
-- name         VARCHAR
-- city         VARCHAR
-- state_prov   VARCHAR
-- country      VARCHAR
-- team_number  INT

-- =============================================
-- TeamsAtEvent
-- =============================================
-- ID        INT  IDENTITY PK
-- frc_team  VARCHAR
-- event_key VARCHAR

-- =============================================
-- REBUILT 2026 Scoring Reference
-- =============================================
-- Auto:   FUEL in Hub → 1pt each
--         Tower Level 1 → 15pts
--         Mobility → 3pts
-- Teleop: FUEL in Hub → 1pt each
--         Tower Level 1 → 10pts
--         Tower Level 2 → 20pts
--         Tower Level 3 → 30pts
-- RPs:    Energized (≥100 FUEL) = 1 RP
--         Supercharged (≥360 FUEL) = 1 RP
--         Traversal (≥50 Tower pts) = 1 RP
